apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astro
  namespace: astro
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: astro
      app.kubernetes.io/name: astro
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: astro
        app.kubernetes.io/name: astro
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: astro
        image: quay.io/fairwinds/astro:v1.2.0
        imagePullPolicy: IfNotPresent
        name: astro
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /metrics
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /metrics
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
      serviceAccount: astro
      serviceAccountName: astro
