version: 2

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export REPO=quay.io/reactiveops/dd-manager' >> ${BASH_ENV}

  docker_build_and_push: &docker_build_and_push
    run:
      name: build and push
      command: |
        docker login quay.io -u="reactiveops+circleci" -p="${quay_token}"
        docker build -t $REPO:$CIRCLE_TAG .
        docker push $REPO:$CIRCLE_TAG

jobs:
  test:
    working_directory: /go/src/github.com/reactiveops/dd-manager
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: GO111MODULE=on go test ./pkg/...
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status ./...
      - run: test -z $(go fmt ./...)
      - run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  build:
    docker:
      - image: quay.io/reactiveops/ci-images:v8.0-alpine
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *docker_build_and_push


workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
