// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datadog/datadog.go

// Package mock_datadog is a generated GoMock package.
package mock_datadog

import (
	gomock "github.com/golang/mock/gomock"
	go_datadog_api "github.com/zorkian/go-datadog-api"
	reflect "reflect"
)

// MockDatadogAPI is a mock of DatadogAPI interface
type MockDatadogAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDatadogAPIMockRecorder
}

// MockDatadogAPIMockRecorder is the mock recorder for MockDatadogAPI
type MockDatadogAPIMockRecorder struct {
	mock *MockDatadogAPI
}

// NewMockDatadogAPI creates a new mock instance
func NewMockDatadogAPI(ctrl *gomock.Controller) *MockDatadogAPI {
	mock := &MockDatadogAPI{ctrl: ctrl}
	mock.recorder = &MockDatadogAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatadogAPI) EXPECT() *MockDatadogAPIMockRecorder {
	return m.recorder
}

// GetMonitorsByTags mocks base method
func (m *MockDatadogAPI) GetMonitorsByTags(tags []string) ([]go_datadog_api.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitorsByTags", tags)
	ret0, _ := ret[0].([]go_datadog_api.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitorsByTags indicates an expected call of GetMonitorsByTags
func (mr *MockDatadogAPIMockRecorder) GetMonitorsByTags(tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitorsByTags", reflect.TypeOf((*MockDatadogAPI)(nil).GetMonitorsByTags), tags)
}

// CreateMonitor mocks base method
func (m *MockDatadogAPI) CreateMonitor(arg0 *go_datadog_api.Monitor) (*go_datadog_api.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMonitor", arg0)
	ret0, _ := ret[0].(*go_datadog_api.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMonitor indicates an expected call of CreateMonitor
func (mr *MockDatadogAPIMockRecorder) CreateMonitor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMonitor", reflect.TypeOf((*MockDatadogAPI)(nil).CreateMonitor), arg0)
}

// UpdateMonitor mocks base method
func (m *MockDatadogAPI) UpdateMonitor(arg0 *go_datadog_api.Monitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMonitor", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMonitor indicates an expected call of UpdateMonitor
func (mr *MockDatadogAPIMockRecorder) UpdateMonitor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMonitor", reflect.TypeOf((*MockDatadogAPI)(nil).UpdateMonitor), arg0)
}

// DeleteMonitor mocks base method
func (m *MockDatadogAPI) DeleteMonitor(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMonitor", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMonitor indicates an expected call of DeleteMonitor
func (mr *MockDatadogAPIMockRecorder) DeleteMonitor(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMonitor", reflect.TypeOf((*MockDatadogAPI)(nil).DeleteMonitor), id)
}
